spring:
    application:
        name: iicanf-ad
    datasource:
        hikari:
            connection-test-query: SELECT 1 FROM DUAL
            minimum-idle: 1
            maximum-pool-size: 5
            pool-name: yourPoolName
            auto-commit: false
        driverClassName: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
#        url: jdbc:mysql://10.1.49.25:64311/merchant-center?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
        url: jdbc:mysql://localhost:3306/merchant-center2?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: root

management:
    security:
        enabled: false

mybatis:
    mapper-locations: 'classpath:mapper/*.xml'

mapper:
    mappers:
        - tk.mybatis.mapper.common.Mapper
    notEmpty: true

